apiVersion: v1
kind: Service
metadata:
  name: pai4-app-service
spec:
  selector:
    app: pai4-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort   # INTENTIONAL: NodePort exposes service externally (Trivy flags this)
